
name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Use the Docker Buildx action to set up the builder instance
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    # Build and push the multi-platform image
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          mscststs/clipboard-sync-socket-server:latest
          mscststs/clipboard-sync-socket-server:${{ github.run_number }}
